const overrideFiles = [
	"src/app/globals.css",
	"src/components/composites/markdown/index.ts",
	"src/app/(site)/(marketing)/_components/layout/Footer.tsx",
	"src/app/(site)/(marketing)/_components/layout/Header.tsx",
	"src/app/(site)/(marketing)/_components/layout/HeaderCompact.tsx",
	"src/app/(site)/(marketing)/_components/layout/HeaderFull.tsx",
	"src/app/(site)/(marketing)/_components/layout/HeaderMenuContent.tsx",
	"src/app/(site)/(marketing)/_components/layout/MarketingShell.tsx",
	"src/app/(site)/(marketing)/_components/layout/marketingNav.ts",
	"src/app/(site)/(marketing)/contact/page.tsx",
	"src/app/(site)/(marketing)/internal/intelligence/_components/InternalCard.tsx",
	"src/app/(site)/(marketing)/internal/intelligence/BenchmarkRunToggle.tsx",
	"src/app/(site)/(marketing)/internal/intelligence/graph/page.tsx",
	"src/app/(site)/(marketing)/internal/intelligence/page.tsx",
	"src/app/(site)/(marketing)/internal/intelligence/TemplateIntelligenceGraph.tsx",
	"src/app/(site)/(marketing)/layout.tsx",
	"src/app/(site)/layout.tsx",
	"src/components/ui/input/choice/ChoiceField.tsx",
	"src/components/ui/input/DateInput.tsx",
	"src/components/ui/input/choice/ChoiceIndicators.tsx",
	"src/components/ui/input/MultiselectInput.tsx",
	"src/components/ui/input/RadioInput.tsx",
	"src/components/ui/input/SelectInput.tsx",
	"src/components/ui/input/TextInput.tsx",
	"src/components/ui/input/ToggleInput.tsx",
	"src/components/ui/overlays/modal/ConfirmationModal.tsx",
	"src/components/ui/overlays/modal/ImageInspectModal.tsx",
	"src/components/ui/overlays/modal/ModalShell.tsx",
	"src/components/ui/overlays/toast/ToastHost.tsx",
	"src/components/ui/primitives/Button.tsx",
	"src/components/ui/primitives/Dropdown.tsx",
	"src/components/ui/primitives/Field.tsx",
	"src/components/ui/primitives/InputFrame.tsx",
	"src/components/ui/primitives/Text.tsx",
	"src/config/routes.ts",
	"src/lib/feedback/toast.ts",
	"src/lib/marketing-content/fallback.ts",
	"src/lib/marketing-content/links.ts",
	"src/lib/marketing-content/resolvers.ts",
	"src/lib/marketing-content/sections/homeHero/HomeHeroSection.tsx",
	"src/lib/marketing-content/types.ts",
	"src/lib/routes.ts",
];

export const thinStartProfile = {
	schemaVersion: 1,
	id: "thin-start",
	description:
		"A complete, minimal Averlo workspace with the shared visual foundation and a filesystem-backed live surface.",
	defaultOutput: ".thin-start/workspace",
	overridesRoot: "template-profiles/thin-start/overrides",
	sharedFiles: [
		"src/components/ui/primitives/Panel.tsx",
		"src/components/ui/primitives/Card.tsx",
	],
	overrides: overrideFiles.map((target) => ({
		source: `template-profiles/thin-start/overrides/${target}`,
		target,
	})),
	removals: [
		"scripts/scroll-performance",
		"src/app/(site)/(auth)",
		"src/app/(site)/_components/settings",
		"src/app/(site)/dashboard",
		"src/app/(site)/(marketing)/settings",
		"src/app/(site)/(marketing)/internal/airbnb-pop",
		"src/app/(site)/(marketing)/internal/demo",
		"src/app/(site)/(marketing)/internal/dictionary",
		"src/app/(site)/(marketing)/internal/playground",
		"src/app/(site)/(marketing)/internal/reference",
		"src/app/(site)/(marketing)/_components/layout/MarketingContentSearch.tsx",
		"src/app/(site)/(marketing)/_components/providers",
		"src/components/domain/search",
		"src/components/composites/markdown/MarkdownEditor.tsx",
		"src/components/composites/markdown/MarkdownEditorClient.tsx",
		"src/components/ui/input/ColorInput.tsx",
		"src/components/ui/input/ColorSwatchInput.tsx",
		"src/components/ui/overlays/modal/ModalForm.tsx",
		"src/components/ui/helpers",
		"src/components/ui/icons",
		"src/components/ui/misc",
		"src/components/ui/time",
		"src/components/ui/input/files",
		"src/components/ui/input/ButtonMultiSelectInput.tsx",
		"src/components/ui/input/ComboboxMultiSelectInput.tsx",
		"src/components/ui/input/ComboboxTextInput.tsx",
		"src/components/ui/input/DateRangeInput.tsx",
		"src/components/ui/input/EditableTextInput.tsx",
		"src/components/ui/input/EmailInput.tsx",
		"src/components/ui/input/NumberInput.tsx",
		"src/components/ui/input/PasswordInput.tsx",
		"src/components/ui/input/PhoneInput.tsx",
		"src/components/ui/input/ProfilePictureInput.tsx",
		"src/components/ui/input/SignaturePad.tsx",
		"src/components/ui/input/SliderInput.tsx",
		"src/components/ui/input/SpamProtectionFields.tsx",
		"src/components/ui/input/TextAreaInput.tsx",
		"src/components/ui/input/UnitNumberInput.tsx",
		"src/components/ui/primitives/Divider.tsx",
	],
	packageChanges: {
		dependencies: {
			add: {
				sonner: "^2.0.7",
			},
			remove: ["@mdxeditor/editor"],
		},
		devDependencies: {
			add: {},
			remove: [],
		},
		scripts: {
			remove: [
				"measure:scroll-performance",
				"record:scroll-performance",
				"setup:scroll-performance-autoresearch",
				"score:scroll-performance",
			],
			retain: [
				"intelligence:generate",
				"intelligence:query",
				"orchestration",
				"orchestration-state",
				"dev",
				"dev:user",
				"dev:agent",
				"dev:thin",
				"build",
				"start",
				"lint",
				"typecheck",
				"verify:static",
				"verify:build",
				"verify:smoke",
				"verify",
				"format",
				"create:thin-start",
				"review:thin-start-api",
				"prune:template",
				"postinstall",
				"postbuild",
			],
		},
	},
	routes: {
		retain: [
			{
				path: "/",
				file: "src/app/(site)/(marketing)/(home)/page.tsx",
			},
			{
				path: "/contact",
				file: "src/app/(site)/(marketing)/contact/page.tsx",
			},
			{
				path: "/internal/intelligence",
				file: "src/app/(site)/(marketing)/internal/intelligence/page.tsx",
			},
			{
				path: "/internal/intelligence/graph",
				file: "src/app/(site)/(marketing)/internal/intelligence/graph/page.tsx",
			},
		],
		remove: ["/login", "/dashboard", "/settings", "/internal/demo"],
	},
	apiReview: {
		allowedUiImports: [
			"@/components/ui/primitives/Button",
			"@/components/ui/primitives/Card",
			"@/components/ui/primitives/Panel",
			"@/components/ui/primitives/Text",
			"@/components/ui/primitives/Section",
			"@/components/ui/primitives/Field",
			"@/components/ui/primitives/InputFrame",
			"@/components/ui/primitives/Dropdown",
			"@/components/ui/primitives/dropdownStyles",
			"@/components/ui/input/choice/ChoiceField",
			"@/components/ui/input/choice/ChoiceIndicators",
			"@/components/ui/input/RadioInput",
			"@/components/ui/input/MultiselectInput",
			"@/components/ui/input/TextInput",
			"@/components/ui/input/SelectInput",
			"@/components/ui/input/ToggleInput",
		],
		allowedUiPrefixes: [
			"@/components/ui/foundations/",
			"@/components/ui/motion",
			"@/components/ui/overlays/",
		],
		allowedCompositePrefixes: ["@/components/composites/markdown"],
		broadUiPrefixes: [
			"@/components/ui/misc/",
			"@/components/ui/helpers/",
			"@/components/ui/icons/",
			"@/components/ui/time/",
		],
		compatibilityMarkerExemptions: [
			"src/components/ui/motion/reveal/legacyCore.tsx",
		],
	},
	verification: {
		requiredFiles: [
			"src/components/ui/primitives/Panel.tsx",
			"src/components/ui/primitives/Card.tsx",
			"src/components/ui/overlays/toast/ToastHost.tsx",
			"src/app/(site)/(marketing)/internal/intelligence/page.tsx",
		],
		forbiddenPaths: [
			"src/app/(site)/dashboard",
			"src/app/(site)/(marketing)/internal/demo",
			"src/components/ui/misc",
			"scripts/scroll-performance",
		],
		forbiddenPackages: ["@mdxeditor/editor"],
		commands: [
			"npm run review:thin-start-api -- --strict",
			"npm run typecheck",
			"npm run build",
		],
	},
};

export default thinStartProfile;
