// components/ui/icons/phosphorRegistry.tsx
"use client";

import {
	ArrowRight,
	ArrowSquareOut,
	ArrowUpIcon,
	Bell,
	Buildings,
	Calendar,
	Cards,
	CaretDown,
	CaretLeftIcon,
	CaretRightIcon,
	Check,
	Copy,
	Database,
	DiscordLogo,
	DotsThreeVertical,
	Eye,
	EyeClosed,
	FlagIcon,
	Gear,
	HouseIcon,
	InstagramLogo,
	LinkedinLogo,
	List,
	Lock,
	MagnifyingGlass,
	MetaLogo,
	Minus,
	PencilSimpleIcon,
	Plus,
	SignOut,
	SlidersHorizontal,
	Spinner,
	Star,
	TiktokLogo,
	Trash,
	UsersThree,
	X,
	XLogo,
	YoutubeLogo,
} from "@phosphor-icons/react";
import {
	createIconRegistry,
	type IconRegistry,
} from "@/components/ui/icons/iconRegistry";

const phosphorOverrides: Partial<IconRegistry> = {
	"arrow-right": ArrowRight,
	"external-link": ArrowSquareOut,
	"caret-left": CaretLeftIcon,
	"caret-right": CaretRightIcon,
	bell: Bell,
	building: Buildings,
	calendar: Calendar,
	cards: Cards,
	chevron: CaretDown,
	"chevron-down": CaretDown,
	check: Check,
	copy: Copy,
	database: Database,
	discord: DiscordLogo,
	"ellipsis-vertical": DotsThreeVertical,
	eye: Eye,
	"eye-closed": EyeClosed,
	instagram: InstagramLogo,
	"arrow-up": ArrowUpIcon,
	"linked-in": LinkedinLogo,
	lock: Lock,
	menu: List,
	meta: MetaLogo,
	minus: Minus,
	search: MagnifyingGlass,
	plus: Plus,
	spinner: Spinner,
	sliders: SlidersHorizontal,
	tiktok: TiktokLogo,
	close: X,
	cross: X,
	flag: FlagIcon,
	gear: Gear,
	home: HouseIcon,
	"log-out": SignOut,
	pencil: PencilSimpleIcon,
	trash: Trash,
	users: UsersThree,
	star: Star,
	x: XLogo,
	youtube: YoutubeLogo,
};

export const phosphorIconRegistry = createIconRegistry(phosphorOverrides);
