// components/ui/icons/phosphorRegistry.tsx
"use client";

import {
	ArrowRight,
	ArrowUpIcon,
	Bell,
	Calendar,
	CaretDown,
	CaretLeftIcon,
	CaretRightIcon,
	Check,
	Copy,
	DiscordLogo,
	DotsThreeVertical,
	Eye,
	EyeClosed,
	FlagIcon,
	InstagramLogo,
	LinkedinLogo,
	List,
	Lock,
	MetaLogo,
	Minus,
	Plus,
	Spinner,
	TiktokLogo,
	X,
	XLogo,
	YoutubeLogo,
} from "@phosphor-icons/react";
import {
	createIconRegistry,
	type IconRegistry,
} from "@/components/ui/icons/iconRegistry";

const phosphorOverrides: Partial<IconRegistry> = {
	"arrow-right": ArrowRight,
	"caret-left": CaretLeftIcon,
	"caret-right": CaretRightIcon,
	bell: Bell,
	calendar: Calendar,
	chevron: CaretDown,
	"chevron-down": CaretDown,
	check: Check,
	copy: Copy,
	discord: DiscordLogo,
	"ellipsis-vertical": DotsThreeVertical,
	eye: Eye,
	"eye-closed": EyeClosed,
	instagram: InstagramLogo,
	"arrow-up": ArrowUpIcon,
	"linked-in": LinkedinLogo,
	lock: Lock,
	menu: List,
	meta: MetaLogo,
	minus: Minus,
	plus: Plus,
	spinner: Spinner,
	tiktok: TiktokLogo,
	close: X,
	cross: X,
	flag: FlagIcon,
	x: XLogo,
	youtube: YoutubeLogo,
};

export const phosphorIconRegistry = createIconRegistry(phosphorOverrides);
